Controllers/ApplicationJoinedUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JOB_FINDER.Models;

namespace JOB_FINDER.Controllers
{
    public class ApplicationJoinedUserController : Controller
    {
        // GET: ApplicationJoinedUser
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobFinderDBEntities db = new JobFinderDBEntities();
            List<APPLICATION> application_date = db.APPLICATIONS.ToList();
            List<USER> user_name = db.USERS.ToList();
            var joinedTable = from a in application_date
                              join u in user_name on a.UserID equals u.UserID
                              where a.PostID == id
                              select new ApplicationJoinedUser { applicationDetails = a, userDetails = u };
            return View(joinedTable);
        }
    }
}

Controllers/POSTsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JOB_FINDER.Models;

namespace JOB_FINDER.Controllers
{
    public class POSTsController : Controller
    {
        private JobFinderDBEntities db = new JobFinderDBEntities();

        // GET: POSTs/Create
        public ActionResult Create()
        {
            //ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name");
            ViewBag.CompanyID = Session["CompanyID"];
            return View();
        }

        // POST: POSTs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PostID,CompanyID,Salary,Location,Experience,Description")] POST pOST)
        {
            if (ModelState.IsValid)
            {
                db.POSTs.Add(pOST);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name", pOST.CompanyID);
            return View(pOST);
        }

        public ActionResult Index(string searchByExp, string searchBySal, string searching)
        {
            if (searchByExp == "0-2")
            {
                if (!String.IsNullOrWhiteSpace(searching))
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary >= 5000 && x.Salary <= 20000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary > 20000 && x.Salary <= 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary > 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Location.Contains(searching)).ToList());
                    }
                }
                else
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary >= 5000 && x.Salary <= 20000).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary > 20000 && x.Salary <= 50000).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary > 50000).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2).ToList());
                    }
                }
            }
            else if (searchByExp == "3-5")
            {
                if (!String.IsNullOrWhiteSpace(searching))
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary >= 5000 && x.Salary <= 20000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary > 20000 && x.Salary <= 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary > 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Location.Contains(searching)).ToList());
                    }
                }
                else
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary >= 5000 && x.Salary <= 20000).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary > 20000 && x.Salary <= 50000).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary > 50000).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5).ToList());
                    }
                }
            }
            else if (searchByExp == "6-10")
            {
                if (!String.IsNullOrWhiteSpace(searching))
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary >= 5000 && x.Salary <= 20000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary > 20000 && x.Salary <= 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary > 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Location.Contains(searching)).ToList());
                    }
                }
                else
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary >= 5000 && x.Salary <= 20000).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary > 20000 && x.Salary <= 50000).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary > 50000).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10).ToList());
                    }
                }
            }
            else
            {
                if (!String.IsNullOrWhiteSpace(searching))
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Salary >= 5000 && x.Salary <= 20000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Salary > 20000 && x.Salary <= 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Salary > 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Location.Contains(searching)).ToList());
                    }
                }
                else
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Salary >= 5000 && x.Salary <= 20000).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Salary > 20000 && x.Salary <= 50000).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Salary > 50000).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.ToList());
                    }
                }
            }
        }

        /*Apply method added for CP 2*/
        public ActionResult Apply(int? id)
        {
            if (Session["UserID"] == null)
            {
                ViewBag.Notification = "Please login first!";
            }
            else
            {

Controllers/REVIEWsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JOB_FINDER.Models;

namespace JOB_FINDER.Controllers
{
    public class REVIEWsController : Controller
    {
        private JobFinderDBEntities db = new JobFinderDBEntities();

        // GET: REVIEWs
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            /*
            USER uSER = db.USERS.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            */
            COMPANY cOMPANY = db.COMPANies.Find(id);
            if (cOMPANY == null)
            {
                return HttpNotFound();
            }
            return View(db.REVIEWs.Where(x => x.CompanyID == id).ToList());
            //var rEVIEWs = db.REVIEWs.Include(r => r.COMPANY).Include(r => r.USER);
            //return View(rEVIEWs.ToList());
        }

        // GET: REVIEWs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            REVIEW rEVIEW = db.REVIEWs.Find(id);
            if (rEVIEW == null)
            {
                return HttpNotFound();
            }
            return View(rEVIEW);
        }

        // GET: REVIEWs/Create
        public ActionResult Create(int? id)
        {
            //ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name");
            //ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name");
            COMPANY cOMPANY = db.COMPANies.Find(id);
            ViewBag.CompanyName = cOMPANY.Name;
            if (Session["UserID"] == null)
            {
                ViewBag.Notification = "Please login first!";
                return View();
            }
            else
            {
                ViewBag.UserID = Session["UserID"];
                ViewBag.CompanyID = id;
                ViewBag.Date = DateTime.Today.ToString("d");
                return View();
            }
        }

        // POST: REVIEWs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReviewID,CompanyID,UserID,Description,ReviewDate")] REVIEW rEVIEW)
        {
            if (Session["UserID"] == null)
            {
                ViewBag.Notification = "Please login first!";
            }
            else
            {
                if (ModelState.IsValid)
                {
                    db.REVIEWs.Add(rEVIEW);
                    db.SaveChanges();
                    return RedirectToAction("SeeCompanyProfile", "COMPANies", new { id = rEVIEW.CompanyID });
                }
            }
            ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name", rEVIEW.CompanyID);
            ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name", rEVIEW.UserID);
            ViewBag.UserID = Session["UserID"];
            return View(rEVIEW);
        }

        // GET: REVIEWs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            REVIEW rEVIEW = db.REVIEWs.Find(id);
            if (rEVIEW == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name", rEVIEW.CompanyID);
            ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name", rEVIEW.UserID);
            return View(rEVIEW);
        }

        // POST: REVIEWs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReviewID,UserID,CompanyID,ReviewDate,Description")] REVIEW rEVIEW)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rEVIEW).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name", rEVIEW.CompanyID);
            ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name", rEVIEW.UserID);
            return View(rEVIEW);
        }

        // GET: REVIEWs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            REVIEW rEVIEW = db.REVIEWs.Find(id);
            if (rEVIEW == null)
            {
                return HttpNotFound();
            }
            return View(rEVIEW);
        }

        // POST: REVIEWs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            REVIEW rEVIEW = db.REVIEWs.Find(id);
            db.REVIEWs.Remove(rEVIEW);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/COMPANies/CompanyProfile.cshtml
@model JOB_FINDER.Models.COMPANY

@{
    ViewBag.Title = "CompanyProfile";
}

<div class="container">
    <div class="row" style="padding-top: 60px; padding-bottom: 50px;">
        <div class="col-md-4" style=" margin-top: 75px;font-size: 20px;">
            <ul class="list-group">
                <li class="list-group-item">@Html.ActionLink("See your previous posts?", "SeePrevPostst", new { id = Model.CompanyID })</li>
                <li class="list-group-item">@Html.ActionLink("Create Post", "Create", "POSTs")</li>
                <li class="list-group-item">@Html.ActionLink("Recruit", "Index", "USERs")</li>
                <li class="list-group-item">@Html.ActionLink("Update Password", "UpdatePassword", "COMPANies")</li>
                <li class="list-group-item">@Html.ActionLink("SignOut", "SignOut", "COMPANies")</li>
            </ul>
        </div>
        <div class="col-md-8">
            <div style="margin-left: 150px;">
                <dl>

                    <dd style="color: #1ba94c; font-size: 45px;">
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt style="font-size: 20px; margin-top: 30px;">
                        About
                    </dt>

                    <dd style="font-size: 15px;">
                        @Html.DisplayFor(model => model.Description)
                    </dd>

                    <dt style="font-size: 20px; margin-top: 30px;">
                        Office Address
                    </dt>

                    <dd style="font-size: 15px;">
                        @Html.DisplayFor(model => model.Address)
                    </dd>

                    <dt style="font-size: 20px; margin-top: 30px;">
                        Phone
                    </dt>

                    <dd style="font-size: 15px;">
                        @Html.DisplayFor(model => model.Phone)
                    </dd>

                    <dt style="font-size: 20px; margin-top: 30px;">
                        Company Email
                    </dt>

                    <dd style="font-size: 15px;">
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                </dl>
            </div>
        </div>
    </div>
</div>

<!--
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CompanyID })
</p>
-->
<!--Second Checkpoint-->
<!---->

<!--
<div>
    <p><a href="/POSTs/Create" class="btn btn-primary btn-lg">Create Post</a></p>
    <p><a href="/USERs/Index" class="btn btn-primary btn-lg">Recruit</a></p>
</div>
-->

Views/COMPANies/ForgotPassword.cshtml
@model JOB_FINDER.Models.COMPANY

@{
    ViewBag.Title = "Forgot Password";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="color: #1ba94c;">
        <div class="form-group">
            <label style="padding-left: 35px; color: #1ba94c;">Enter the email that was used while creating account</label>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send Mail" class="btn btn-default"  style="background-color: #1ba94c; color: white;"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <label>@ViewBag.Notification</label>
            </div>
        </div>
    </div>
}

Views/COMPANies/Login.cshtml
@model JOB_FINDER.Models.TempCompany

@{
    ViewBag.Title = "Login";
    var msg = ViewBag.LoginFailed;
}

<div class="container">
    <div class="row" style="padding-bottom: 80px;">
        <div class="col-md-8" style="padding-top: 40px; text-align: center;">
            <img style="height: 350px;" src="~/images/onlinelogomaker-092221-2227-9311.svg">
        </div>
        <div class="col-md-4" style="color: #1ba94c; padding-top: 75px; font-size: 18px;">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal" style="color: #1ba94c;">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <p>Email</p>
                    <div class="">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p>Password</p>
                    <div class="">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="">
                        <input type="submit" value="Login" class="btn btn-default" style="background-color: #1ba94c; color: white;" />
                    </div>
                </div>

                <div class="form-group">
                    <a href="/COMPANies/ForgotPassword" style="color: #1ba94c; text-decoration: none;">Forgot Password?</a>
                </div>

                <div class="form-group">
                    <div class="">
                        <a href="/COMPANies/SignUp" style="color: #1ba94c; text-decoration: none;">Don't have an account?</a>
                    </div>
                </div>

            </div>
            }
        </div>
    </div>
</div>

@if (msg != null)
{
    <p class="text-danger">@msg</p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/COMPANies/SeeCompanyProfile.cshtml
@model IEnumerable<JOB_FINDER.Models.COMPANY>

@{
    ViewBag.Title = "SeeCompanyProfile";
}

<div style="padding: 50px;">

    @foreach (var item in Model)
    {
        <div class="container" style="padding: 30px;">
            <div class="row">
                <div class="col-md-7">

                    <div style="margin-left: 0px; border: 0.5px solid #e2e0e0; border-radius: 10px; box-shadow: 1.5px 1.5px 1.5px 1.5px #ded8d8; padding: 50px;">
                        <p style="font-size: 20px;">
                            <text style="color: #1ba94c;">Name: </text>@Html.DisplayFor(modelItem => item.Name)
                        </p>
                        <p style="font-size: 20px;">
                            <text style="color: #1ba94c;">About: </text>@Html.DisplayFor(modelItem => item.Description)
                        </p>
                        <p style="font-size: 20px;">
                            <text style="color: #1ba94c;">Phone Number: </text>@Html.DisplayFor(modelItem => item.Phone)
                        </p>
                        <p style="font-size: 20px;">
                            <text style="color: #1ba94c;">Email: </text>@Html.DisplayFor(modelItem => item.Email)
                        </p>
                        <p style="font-size: 20px;">
                            <text style="color: #1ba94c;">Present Address: </text>@Html.DisplayFor(modelItem => item.Address)
                        </p>
                    </div>


                </div>
                <div class="col-md-5" style="margin-top: 0px;">
                    <ul class="list-group" style="font-size: 20px;">
                        <a style="text-decoration: none; color: #1ba94c;">
                        <li class="list-group-item" onclick="location.href='@Url.Action("Create", "REVIEWs", new { id = item.CompanyID })'">Give a review</li>
                        </a>
                        <a style="text-decoration: none; color: #1ba94c;">
                        <li class="list-group-item" onclick="location.href='@Url.Action("Index", "REVIEWs", new { id = item.CompanyID })'">See reviews about this company</li>
                        </a>
                    </ul>
                </div>
            </div>
        </div>
    }

    
</div>

Views/COMPANies/SeePrevPostst.cshtml
@model IEnumerable<JOB_FINDER.Models.POST>

@{
    ViewBag.Title = "SeePrevPostst";
}

<h2 class="text-center" style="margin-bottom: 35px; margin-top: 35px;">Your previous posts</h2>

<table class="table text-left" style="font-size: 23px;">

    @if (Model.Count() == 0)
    {
        <div class="form-group text-center" style="margin-top: 75px; margin-bottom: 40px;">
            <p style="font-size: 50px;" class=text-danger>You haven't posted anything yet!</p>
        </div>

        <div class="form-group text-center" style="margin-bottom: 50px;">
            <img style="height: 300px;" src="~/images/onlinelogomaker-101321-0450-4374.png">
        </div>
    }
    else
    {


        <div class="container" style="margin-top: 15px; margin-bottom: 15px; border: 0.5px solid #e2e0e0; border-radius: 10px; box-shadow: 1.5px 1.5px 1.5px 1.5px #ded8d8; padding: 15px;">
            <div class="row" style="padding: 5px;">
                @foreach (var item in Model)
                {
                    <div class="col">
                        <h3 class="card-title" style="color: #1ba94c;">@Html.DisplayFor(modelItem => item.Description)</h3>
                        <p class="card-text">@Html.DisplayNameFor(model => model.Location): @Html.DisplayFor(modelItem => item.Location)</p>
                        <p class="card-text">@Html.DisplayNameFor(model => model.Experience): @Html.DisplayFor(modelItem => item.Experience) Years</p>
                        <p class="card-text">@Html.DisplayNameFor(model => model.Salary): @Html.DisplayFor(modelItem => item.Salary) Tk.</p>
                        <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "ApplicationJoinedUser", new { id = item.PostID })'">See Applications</button>
                    </div>
                }
            </div>
        </div>
    }

</table>

Views/COMPANies/SignUp.cshtml
@model JOB_FINDER.Models.COMPANY

@{
    ViewBag.Title = "SignUp";
}

<div class="container">
    <div class="row">
        <div class="col-md-6" style="padding-top: 40px;">
            <img style="height: 400px;" src="~/images/onlinelogomaker-092221-2227-9311.svg">
        </div>
        <div class="col-md-6" style="color: #1ba94c; font-size: 15.5px;">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <p>What's your company's name?</p>
                    <div class="">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p>Write something about your institution</p>
                    <div class="">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p>Current Address</p>
                    <div class="">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p>Phone Number</p>
                    <div class="">
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p>Enter Email</p>
                    <div class="">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p>Enter Password</p>
                    <div class="">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p>Confirm Password</p>
                    <div class="">
                        @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <input type="submit" value="Register" class="btn btn-default" style="background-color: #1ba94c; color: white;" />
                </div>

                <div class="form-group">
                    <a href="/COMPANies/Login" style="color: #1ba94c; text-decoration: none;">Already have an account?</a>
                </div>

            </div>
            }
        </div>
    </div>
</div>

<!--
<div>
    <p><a href="/COMPANies/Login" class="btn btn-primary btn-lg">Login &raquo;</a></p>
</div>
-->

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}