Models/USER.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_FINDER.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.APPLICATIONS = new HashSet<APPLICATION>();
            this.RECOMMENDATIONs = new HashSet<RECOMMENDATION>();
            this.REVIEWs = new HashSet<REVIEW>();
        }


        public int UserID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]
        public string Email { get; set; }
        [Required]
        public string Phone { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [StringLength(18, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        public string Password { get; set; }
        public string University { get; set; }
        public string Description { get; set; }
        public string Skill { get; set; }
        public string CV { get; set; }


        [NotMapped] // Does not effect with your database
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        //for Final checkpoint

        [NotMapped]
        [DataType(DataType.Password)]
        public string OldPassword { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICATION> APPLICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECOMMENDATION> RECOMMENDATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEW> REVIEWs { get; set; }
    }
}

Controllers/APPLICATIONsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JOB_FINDER.Models;

namespace JOB_FINDER.Controllers
{
    public class APPLICATIONsController : Controller
    {
        private JobFinderDBEntities db = new JobFinderDBEntities();

        // GET: APPLICATIONs
        public ActionResult Index()
        {
            //var aPPLICATIONS = db.APPLICATIONS.Include(a => a.POST).Include(a => a.USER);
            //return View(aPPLICATIONS.ToList());
            /*
            2nd Checkpoint
            */
            int id = (int)Session["UserID"];
            //var aPPLICATIONS = db.APPLICATIONS.Include(a => a.POST).Include(a => a.USER);
            //APPLICATION aPPLICATION = db.APPLICATIONS.Find(id);
            return View(db.APPLICATIONS.Where(x => x.UserID == id).ToList());
        }

        // GET: APPLICATIONs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            APPLICATION aPPLICATION = db.APPLICATIONS.Find(id);
            if (aPPLICATION == null)
            {
                return HttpNotFound();
            }
            return View(aPPLICATION);
        }

        // GET: APPLICATIONs/Create
        public ActionResult Create()
        {
            ViewBag.PostID = new SelectList(db.POSTs, "PostID", "Location");
            ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name");
            return View();
        }

        // POST: APPLICATIONs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ApplicationID,UserID,PostID,ApplicationDate")] APPLICATION aPPLICATION)
        {
            if (ModelState.IsValid)
            {
                db.APPLICATIONS.Add(aPPLICATION);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PostID = new SelectList(db.POSTs, "PostID", "Location", aPPLICATION.PostID);
            ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name", aPPLICATION.UserID);
            return View(aPPLICATION);
        }

        // GET: APPLICATIONs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            APPLICATION aPPLICATION = db.APPLICATIONS.Find(id);
            if (aPPLICATION == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostID = new SelectList(db.POSTs, "PostID", "Location", aPPLICATION.PostID);
            ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name", aPPLICATION.UserID);
            return View(aPPLICATION);
        }

        // POST: APPLICATIONs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ApplicationID,UserID,PostID,ApplicationDate")] APPLICATION aPPLICATION)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aPPLICATION).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PostID = new SelectList(db.POSTs, "PostID", "Location", aPPLICATION.PostID);
            ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name", aPPLICATION.UserID);
            return View(aPPLICATION);
        }

        // GET: APPLICATIONs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            APPLICATION aPPLICATION = db.APPLICATIONS.Find(id);
            if (aPPLICATION == null)
            {
                return HttpNotFound();
            }
            return View(aPPLICATION);
        }

        // POST: APPLICATIONs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            APPLICATION aPPLICATION = db.APPLICATIONS.Find(id);
            db.APPLICATIONS.Remove(aPPLICATION);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/RECOMMENDATIONsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JOB_FINDER.Models;

namespace JOB_FINDER.Controllers
{
    public class RECOMMENDATIONsController : Controller
    {
        private JobFinderDBEntities db = new JobFinderDBEntities();

        // GET: RECOMMENDATIONs
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER uSER = db.USERS.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            return View(db.RECOMMENDATIONs.Where(x => x.UserID == id).ToList());
            //var rECOMMENDATIONs = db.RECOMMENDATIONs.Include(r => r.COMPANY).Include(r => r.USER);
            //return View(rECOMMENDATIONs.ToList());
        }

        // GET: RECOMMENDATIONs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RECOMMENDATION rECOMMENDATION = db.RECOMMENDATIONs.Find(id);
            if (rECOMMENDATION == null)
            {
                return HttpNotFound();
            }
            return View(rECOMMENDATION);
        }

        // GET: RECOMMENDATIONs/Create
        public ActionResult Create(int? id)
        {
            USER uSER = db.USERS.Find(id);
            ViewBag.UserName = uSER.Name;

            ViewBag.UserID = id;
            ViewBag.CompanyID = Session["CompanyID"];
            ViewBag.Date = DateTime.Today.ToString("d");
            return View();
        }

        // POST: RECOMMENDATIONs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RecommendationID,CompanyID,UserID,Description,RecommendationDate")] RECOMMENDATION rECOMMENDATION)
        {
            if (ModelState.IsValid)
            {
                db.RECOMMENDATIONs.Add(rECOMMENDATION);
                db.SaveChanges();
                return RedirectToAction("SeeApplicantProfile", "USERs", new { id = rECOMMENDATION.UserID });
            }

            ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name", rECOMMENDATION.CompanyID);
            ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name", rECOMMENDATION.UserID);
            return View(rECOMMENDATION);
        }

        // GET: RECOMMENDATIONs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RECOMMENDATION rECOMMENDATION = db.RECOMMENDATIONs.Find(id);
            if (rECOMMENDATION == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name", rECOMMENDATION.CompanyID);
            ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name", rECOMMENDATION.UserID);
            return View(rECOMMENDATION);
        }

        // POST: RECOMMENDATIONs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RecommendationID,CompanyID,UserID,Description,RecommendationDate")] RECOMMENDATION rECOMMENDATION)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rECOMMENDATION).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name", rECOMMENDATION.CompanyID);
            ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name", rECOMMENDATION.UserID);
            return View(rECOMMENDATION);
        }

        // GET: RECOMMENDATIONs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RECOMMENDATION rECOMMENDATION = db.RECOMMENDATIONs.Find(id);
            if (rECOMMENDATION == null)
            {
                return HttpNotFound();
            }
            return View(rECOMMENDATION);
        }

        // POST: RECOMMENDATIONs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RECOMMENDATION rECOMMENDATION = db.RECOMMENDATIONs.Find(id);
            db.RECOMMENDATIONs.Remove(rECOMMENDATION);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/USERs/ChangePassword.cshtml
@model JOB_FINDER.Models.USER

@{
    ViewBag.Title = "ChangePassword";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal" style="color: #1ba94c;">
    <div class="form-group">
        <label style="padding-left: 35px; color: #1ba94c;">Enter the email that was used while creating account</label>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Send Mail" class="btn btn-default" style="background-color: #1ba94c; color: white;"/>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <label>@ViewBag.Notification</label>
        </div>
    </div>

</div>
}

Views/USERs/Create.cshtml
@model JOB_FINDER.Models.USER

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>USER</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.University, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.University, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.University, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Skill, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Skill, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Skill, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/USERs/Delete.cshtml
@model JOB_FINDER.Models.USER

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>USER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.University)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.University)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Skill)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Skill)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CV)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/USERs/Details.cshtml
@model JOB_FINDER.Models.USER

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>USER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.University)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.University)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Skill)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Skill)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CV)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/USERs/Index.cshtml
@model IEnumerable<JOB_FINDER.Models.USER>

@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("Index", "USERs", FormMethod.Get))
{
    <div style="padding: 5px; margin-top: 25px; margin-bottom: 15px; font-size: 20px; text-align: center">
        <h3 style="margin-top: 50px; margin-bottom: 25px;">What skills are you looking for?</h3>
        <div style="margin-bottom: 50px;">
            @Html.TextBox("Searching")
            <input type="submit" value="Search" class="btn btn-success" style="font-size: 18px;" />
        </div>
    </div>
}

<div class="container">
    @if (Model.Count() == 0)
    {
        <h2>Nothing Found!</h2>
    }
    else
    {
        foreach (var item in Model)
        {

            <div style="border: 0.5px solid #e2e0e0; border-radius: 10px; box-shadow: 1.5px 1.5px 1.5px 1.5px #ded8d8; margin: 25px;">
                <div style="padding: 20px; margin-top: 10px; margin-bottom: 10px;">
                    <span style="font-size: 20px;">
                        @Html.DisplayFor(modelItem => item.Name)
                    </span>
                    <span class="" style="font-size: 15px; color: #1ba94c; margin-left: 25px;">
                        @Html.DisplayNameFor(model => model.Skill): @Html.DisplayFor(modelItem => item.Skill)                   
                    </span>
                    <span style="float: right;">
                        @Html.ActionLink("View Profile", "SeeApplicantProfile", "USERs", new { id = item.UserID }, null)
                    </span>
                </div>
            </div>

        }
    }
</div>

Views/USERs/SeeApplicantProfile.cshtml
@model IEnumerable<JOB_FINDER.Models.USER>

@{
    ViewBag.Title = "SeeApplicantProfile";
}

@foreach (var item in Model)
{
    <div class="container" style="padding: 30px;">
        <div class="row">
            <div class="col-md-7">

                <div style="margin-left: 0px; border: 0.5px solid #e2e0e0; border-radius: 10px; box-shadow: 1.5px 1.5px 1.5px 1.5px #ded8d8; padding: 50px;">
                    <p style="font-size: 20px;">
                        <text style="color: #1ba94c;">Name: </text>@Html.DisplayFor(modelItem => item.Name)
                    </p>
                    <p style="font-size: 20px;">
                        <text style="color: #1ba94c;">Phone Number: </text>@Html.DisplayFor(modelItem => item.Phone)
                    </p>
                    <p style="font-size: 20px;">
                        <text style="color: #1ba94c;">Email: </text>@Html.DisplayFor(modelItem => item.Email)
                    </p>
                    <p style="font-size: 20px;">
                        <text style="color: #1ba94c;">University: </text>@Html.DisplayFor(modelItem => item.University)
                    </p>
                    <p style="font-size: 20px;">
                        <text style="color: #1ba94c;">Special Skill: </text>@Html.DisplayFor(modelItem => item.Skill)
                    </p>
                    <p style="font-size: 20px;">
                        <text style="color: #1ba94c;">Present Address: </text>@Html.DisplayFor(modelItem => item.Address)
                    </p>
                    @if (item.CV == null)
                    {
                        <p style="font-size: 20px;" class="text-danger">No CV found.</p>
                    }
                    else
                    {
                        <p style="font-size: 20px; color: #1ba94c;">CV: @Html.ActionLink("Download", "Download", "USERs", new { fileName = item.CV }, null)</p>
                    }
                </div>


            </div>
            <div class="col-md-5" style="margin-top: 0px;">
                <ul class="list-group" style="font-size: 20px;">
                    <a style="text-decoration: none; color: #1ba94c;">
                    <li class="list-group-item" onclick="location.href='@Url.Action("Create", "RECOMMENDATIONs", new { id = item.UserID })'">Give a recommendation</li>
                    </a>
                    <a style="text-decoration: none; color: #1ba94c;">
                    <li class="list-group-item" onclick="location.href='@Url.Action("Index", "RECOMMENDATIONs", new { id = item.UserID })'">See recommendations about this user</li>
                    </a>
                </ul>
            </div>
        </div>
    </div>
}

Views/USERs/ViewProfile.cshtml
@model JOB_FINDER.Models.USER

@{
    ViewBag.Title = "ViewProfile";
}

<div class="container">
    <div class="row" style="padding-top: 60px; padding-bottom: 50px;">
        <div class="col-md-4" style=" margin-top: 75px;font-size: 20px;">
            <ul class="list-group">
                <li class="list-group-item">@Html.ActionLink("Show Applications", "Index", "APPLICATIONs")</li>
                <li class="list-group-item">@Html.ActionLink("EditProfile", "EditProfile", "USERs")</li>
                <li class="list-group-item">@Html.ActionLink("Update Password", "UpdatePassword", "USERs")</li>
                <li class="list-group-item">@Html.ActionLink("SignOut", "SignOut", "USERs")</li>
            </ul>
        </div>
        <div class="col-md-8">
            <div style="margin-left: 150px;">
                <dl>
                    <dd style="font-size: 45px;">
                        Welcome, <text style="color: #1ba94c;">@Html.DisplayFor(model => model.Name)</text> 
                    </dd>

                    <dt style="font-size: 20px; margin-top: 30px;">
                        About
                    </dt>

                    <dd style="font-size: 15px;">
                        @Html.DisplayFor(model => model.Description)
                    </dd>

                    <dt style="font-size: 20px; margin-top: 30px;">
                        Current Address
                    </dt>

                    <dd style="font-size: 15px;">
                        @Html.DisplayFor(model => model.Address)
                    </dd>

                    <dt style="font-size: 20px; margin-top: 30px;">
                        Phone
                    </dt>

                    <dd style="font-size: 15px;">
                        @Html.DisplayFor(model => model.Phone)
                    </dd>

                    <dt style="font-size: 20px; margin-top: 30px;">
                        Personal Email
                    </dt>

                    <dd style="font-size: 15px;">
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                    <dt style="font-size: 20px; margin-top: 30px;">
                        University
                    </dt>

                    <dd style="font-size: 15px;">
                        @Html.DisplayFor(model => model.University)
                    </dd>

                    <dt style="font-size: 20px; margin-top: 30px;">
                        Special Skill
                    </dt>

                    <dd style="font-size: 15px;">
                        @Html.DisplayFor(model => model.Skill)
                    </dd>

                    <dt style="font-size: 20px; margin-top: 30px;">
                        @Html.DisplayNameFor(model => model.CV)
                    </dt>

                    <dd style="font-size: 15px;">
                        @if (@ViewBag.Message != null)
                        {
                            @ViewBag.Message
                        }
                        else
                        {
                            @Html.ActionLink("Download", "Download", "USERs", new { fileName = Model.CV }, null)
                        }
                    </dd>

                </dl>
            </div>
        </div>
    </div>
</div>